version: "3.7"
services:
  db:
    image: postgres
    container_name: database_chat
    command:
      -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - my-network

  backend:
    build:
      context: .
    env_file:
      - .env
    container_name: backend
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
    command: [ "/code/backend/docker/app.sh" ]
    restart: on-failure
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
