version: "3.7"
services:
  db:
    image: postgres
    container_name: database
    command:
      -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - my-network

  test_db:
    image: postgres
    container_name: test_database
    command:
      -p 5555
    expose:
      - 5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
