"""add logs details

Revision ID: 30eef4528a84
Revises: 81f1fe4f7c06
Create Date: 2023-04-15 15:17:34.396493

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '30eef4528a84'
down_revision = '81f1fe4f7c06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'details')
    # ### end Alembic commands ###
