"""add logs

Revision ID: 81f1fe4f7c06
Revises: ff04f4b9e058
Create Date: 2023-04-15 15:02:34.221654

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '81f1fe4f7c06'
down_revision = 'ff04f4b9e058'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('action', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
