"""add chat instances

Revision ID: 8c4d98145850
Revises: 81f1fe4f7c06
Create Date: 2023-04-15 19:47:02.589351

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8c4d98145850'
down_revision = '81f1fe4f7c06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('type')
                    )
    types_table = sa.Table('types', sa.MetaData(), autoload_with=op.get_bind())
    op.bulk_insert(types_table, [
        {'id': 0, 'type': 'Personal'},
        {'id': 1, 'type': 'Group'}
    ])
    op.create_table('chats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('chatsusers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id', 'chat_id', 'user_id')
                    )
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
                    sa.Column('body', sa.LargeBinary(), nullable=True),
                    sa.Column('chat_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chatsusers')
    op.drop_table('chats')
    op.drop_table('types')
    # ### end Alembic commands ###
