"""add chat instances

Revision ID: d363835e5f7e
Revises: 81f1fe4f7c06
Create Date: 2023-04-15 16:21:09.478781

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd363835e5f7e'
down_revision = '81f1fe4f7c06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatsusers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id', 'chat_id', 'user_id')
                    )
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'chat_id')
    op.drop_table('chatsusers')
    # ### end Alembic commands ###
